using System;
using System.IO;
using System.Text;
using MdxLib.Model;
using MdxLib.ModelFormats.Mdx;

namespace MdxLib.ModelFormats
{
	/// <summary>
	/// Handles the MDX model format. Can load and save MDX models.
	/// </summary>
	public sealed class CMdx : IModelFormat
	{
		/// <summary>
		/// Default constructor.
		/// </summary>
		public CMdx()
		{
		}

		/// <summary>
		/// Loads a model from a stream.
		/// </summary>
		/// <param name="Name">The name of the model (only used in some error messages)</param>
		/// <param name="Stream">The stream to load from (must support reading)</param>
		/// <param name="Model">The model to load to (must be an empty model)</param>
		public void Load(string Name, Stream Stream, MdxLib.Model.CModel Model)
		{
			if (!Stream.CanRead)
			{
				throw new NotSupportedException("Unable to load \"" + Name + "\", the stream does not support reading!");
			}
			CLoader cLoader = new CLoader(Name, Stream);
			MdxLib.ModelFormats.Mdx.CModel.Instance.Load(cLoader, Model);
			cLoader.Attacher.Attach();
		}

		/// <summary>
		/// Saves a model to a stream.
		/// </summary>
		/// <param name="Name">The name of the model (only used in some error messages)</param>
		/// <param name="Stream">The stream to save to (must support writing and seeking)</param>
		/// <param name="Model">The model to save from</param>
		public void Save(string Name, Stream Stream, MdxLib.Model.CModel Model)
		{
			if (!Stream.CanWrite)
			{
				throw new NotSupportedException("Unable to load \"" + Name + "\", the stream does not support writing!");
			}
			if (!Stream.CanSeek)
			{
				throw new NotSupportedException("Unable to save \"" + Name + "\", the stream does not support seeking!");
			}
			CSaver saver = new CSaver(Name, Stream);
			MdxLib.ModelFormats.Mdx.CModel.Instance.Save(saver, Model, BuildHeader(Name));
		}

		private string BuildHeader(string Name)
		{
			StringBuilder stringBuilder = new StringBuilder();
			stringBuilder.Append(Name.Replace("\n", "").Replace("\r", ""));
			stringBuilder.Append(", ");
			stringBuilder.Append("Generated by MdxLib v1.04 (written by Magnus Ostberg, aka Magos)");
			stringBuilder.Append(", ");
			stringBuilder.Append(DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss"));
			stringBuilder.Append(", ");
			stringBuilder.Append("http://www.magosx.com");
			return stringBuilder.ToString();
		}
	}
}
